### ISSUE TITLE
Pugilist Fisticuffs

### ISSUE THREAD

**Issue by Mythacri** [Mythacri/Mythacri-Foundry-Scripts#111]
The Pugilist has stronger unarmed strikes with their boxing style; called fisticuffs. Pugilist also can use pugilist weapons.

The pugilist weapons include simple weapons without the two-handed property, whips, and improvised weapons. When using a pugilist weapon a character cannot use the finesse property. This needs to be taken into account.

**Comment by krbz999** [comment]
This could be fun to add, but a low priority if the player has no intention of using weapons, only unarmed strikes.

**Comment by NMyers17** [comment]
Main intention is to use mainly unarmed strikes, however I also want to use a whip as I feel the flavour of this could be awesome.

Priority wise though setting up said whip manually is an easy fix for the meantime and a non issue.

**Comment by krbz999** [comment]
A few edge cases that @NMyers17 and @Mythacri can consider:

- If you use a 'flame tongue whip' that deals an additional +1d4 fire damage, do you ignore the fire damage when using it as a pugilist weapon?
- If you use a +1 weapon as a pugilist weapon, do you ignore the +1 to damage?
- If you use a +1 weapon as a pugilist weapon, do you ignore the +1 to attack?
- When you use a pugilist weapon, do you ignore your Strength modifier?

**Comment by NMyers17** [comment]
Additional Weapon effects should not be ignored, as the Pugilist is only altering the base damage and ability used for the attack.

Not doing this would absolutely break bounded accuracy, as its a choice of having a base + to hit vs an AC which takes into account that you have a magical weapon for balance or making a class feature useless in order to use a magic weapon.

Pugilist Weapons use Strength, its the same process as the Monk conversion for Martial Arts, but instead of Dex we use Strength. You wouldn't ignore Strength the Strength Modifier.

Weapon Dice becomes Pugilist Dice if the damage dice for said weapon is lower than the Pugilist Dice value. aka 1d4 becomes 1d6, but 1d8 stays 1d8 until the Pugilist Dice exceed that value (such as when they become 1d10). Modifier should always be replaced by Strength for Pugilist Weapons.

**Comment by krbz999** [comment]
> Weapon Dice becomes Pugilist Dice if the damage dice for said weapon is lower than the Pugilist Dice value. aka 1d4 becomes 1d6, but 1d8 stays 1d8 until the Pugilist Dice exceed that value (such as when they become 1d10). Modifier should always be replaced by Strength for Pugilist Weapons.

What in the case of a whip that deals `1d4 + @mod` and an additional `1d4`, while the Pugilist die is 1d6? Does only the first die get replaced, or do all dice?

**Comment by NMyers17** [comment]
Yes should only ever be the first die thats replaced. First die will always be the base damage of the weapon, with the extra 1d4 being additional, which wouldn't be tied to how Fisticuffs scales.
